id: I9F3B7476
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:06:32+00:00'
last_modified: '2022-06-07T17:17:36.469241+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14009
  title: འཕྲང་དུ་ལུས་པའི་སེམས་ཀྱི་གནས་བབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '7987':
      image_group_id: I1KG14319
      title: ''
      total_pages: 350
      order: 1
      base_file: 7987.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
