id: P003061
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:37:48.822678
source_metadata:
  id: bdr:W1KG14009
  title: འཕྲང་དུ་ལུས་པའི་སེམས་ཀྱི་གནས་བབ།
  author: ''
  volumes:
    977f5249290e4075b28e52a3a0be719a:
      image_group_id: I1KG14319
      title: ''
      volume_number: 1
      total_pages: 350
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
